params:
  initial_prompt: 'PROMPT1'
  temperature: 0.0
  # final, test, eval, train, end
  split: '0-300'
  success: True
  query_category: True
  intra_task: True
  act_obs: True
  analogy_len: 10
  num_retrieval: 3
  reward_weight: 1
  max_init_prompt_len: 6400
